select ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
from ANIMAL_INS ai
JOIN ANIMAL_OUTS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE ai.SEX_UPON_INTAKE LIKE 'Intact%' and (ao.SEX_UPON_OUTCOME LIKE 'Spayed%' or ao.SEX_UPON_OUTCOME LIKE 'Neutered%')