name: Convert Commit to Issue
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    create_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # 모든 커밋을 가져오기 위해
            - name: Create Issue for Commit
              env:
                  GITHUB_TOKEN: ${{ secrets.ACC_TKN }}
              run: |
                  git log ${{ github.event.before }}..${{ github.event.after }} --format='%H' | while read commit_hash; do
                    COMMIT_MESSAGE=$(git log -1 --format=%B $commit_hash)
                    COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
                    COMMIT_BODY=$(echo "$COMMIT_MESSAGE" | awk '/^$/ {seen_blank=1; next} seen_blank {print}')
                    
                    echo "Commit Title: $COMMIT_TITLE"
                    echo "Commit Body: $COMMIT_BODY"
                    echo "Files changed in this commit: $COMMITTED_FILES"

                    problem_title=$(echo "$COMMIT_TITLE" | awk -F 'Title: |,' '{print $2}')

                    if [[ -z "$problem_title" ]]; then
                        echo "This commit is not by algorithm solving."
                    elif [[ $COMMIT_TITLE == [* ]]; then
                        echo "문제: $problem_title"
                        echo "Creating issue for commit starting with ["
                        
                        COMMITTED_FILES=$(git diff-tree --no-commit-id --name-only -r $commit_hash)
                        echo $COMMITTED_FILES
                        
                        # Initializing an empty string for the links
                        COMMITTED_FILES_LINKS=""
                        
                        # Looping through each committed file to create a Markdown link
                        for file in $COMMITTED_FILES; do
                            decoded_file=$(printf "%b" "$file")
                            # Replace this with your GitHub repository details
                            file_url="https://github.com/$GITHUB_REPOSITORY/blob/main/$decoded_file"
                            COMMITTED_FILES_LINKS+="- [$decoded_file]($file_url)\n"
                        done

                        # Use gh issue list and grep to find an issue by title
                        existing_issue=$(gh issue list --repo "$GITHUB_REPOSITORY" | grep "$problem_title" | awk '{print $1}')

                        if [[ ! -z "$existing_issue" ]]; then
                            echo "Issue already exists with title: $problem_title, Issue Number: $existing_issue"
                            # Create a comment on the existing issue
                            comment_body=$(echo -e "A new commit has been made that references this issue.\n\n**Committed Files:**\n$COMMITTED_FILES_LINKS")
                            gh issue comment $existing_issue --body "$comment_body" --repo "$GITHUB_REPOSITORY"
                        else
                            # No existing issue found, proceed to create a new issue
                            issue_body=$(echo -e "This issue was automatically generated from a commit.\n\n**Committed Files:**\n$COMMITTED_FILES_LINKS")
                            issue_response=$(gh issue create --title "$problem_title" --body "$issue_body" --repo "$GITHUB_REPOSITORY" --assignee @me --label "auto-generated")
                            echo "New issue created: $issue_response"
                        fi
                    fi
                  done
