name: Convert Commit to Issue
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    create_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # 모든 커밋을 가져오기 위해
            - name: Create Issue for Commit
              env:
                  GITHUB_TOKEN: ${{ secrets.ACC_TKN }}
              run: |
                  git log ${{ github.event.before }}..${{ github.event.after }} --format='%H' | while read commit_hash; do
                    COMMIT_MESSAGE=$(git log -1 --format=%B $commit_hash)
                    COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
                    COMMIT_BODY=$(echo "$COMMIT_MESSAGE" | awk '/^$/ {seen_blank=1; next} seen_blank {print}')
                    
                    echo "Commit Title: $COMMIT_TITLE"
                    echo "Commit Body: $COMMIT_BODY"
                    echo "Files changed in this commit: $COMMITTED_FILES"

                    problem_title=$(echo "$COMMIT_TITLE" | awk -F 'Title: |, Time:' '{print $2}')

                    if [[ -z "$problem_title" ]]; then
                        echo "This commit is not by algorithm solving."
                    elif [[ $COMMIT_TITLE == [* ]]; then
                        echo "문제: $problem_title"
                        echo "Creating issue for commit starting with ["
                        COMMITTED_FILES=$(git diff-tree --no-commit-id --name-only -r $commit_hash)
                        read -r -d '' issue_body <<EOF
This issue was automatically generated from a commit.

**Commit Message:**
$COMMIT_BODY

**Committed Files:**
$COMMITTED_FILES
EOF

                        issue_response=$(gh issue create --title "$problem_title" --body "$issue_body" --repo "${GITHUB_REPOSITORY}" --assignee @me --label "auto-generated")
                        echo "Issue created: $issue_response"
                    fi
                  done
